### ISSUE TITLE
生产环境运行久了会报openai连接不到网络错误

### ISSUE THREAD

**Issue by lzsnolimit** [lzsnolimit/youqu#112]

**Comment by lzsnolimit** [comment]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 66, in map_httpcore_exceptions
    yield
  File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 228, in handle_request
    resp = self._pool.handle_request(req)
  File "/usr/local/lib/python3.9/site-packages/httpcore/_sync/connection_pool.py", line 248, in handle_request
    raise exc
  File "/usr/local/lib/python3.9/site-packages/httpcore/_sync/connection_pool.py", line 239, in handle_request
    connection = status.wait_for_connection(timeout=timeout)
  File "/usr/local/lib/python3.9/site-packages/httpcore/_sync/connection_pool.py", line 36, in wait_for_connection
    self._connection_acquired.wait(timeout=timeout)
  File "/usr/local/lib/python3.9/site-packages/httpcore/_synchronization.py", line 232, in wait
    raise PoolTimeout()  # pragma: nocover
httpcore.PoolTimeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/openai/_base_client.py", line 858, in _request
    response = self._client.send(request, auth=self.custom_auth, stream=stream)
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 901, in send
    response = self._send_handling_auth(
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 929, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 966, in _send_handling_redirects
    response = self._send_single_request(request)
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1002, in _send_single_request
    response = transport.handle_request(request)
  File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 228, in handle_request
    resp = self._pool.handle_request(req)
  File "/usr/local/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 83, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.PoolTimeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 66, in map_httpcore_exceptions
    yield
  File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 228, in handle_request
    resp = self._pool.handle_request(req)
  File "/usr/local/lib/python3.9/site-packages/httpcore/_sync/connection_pool.py", line 248, in handle_request
    raise exc
  File "/usr/local/lib/python3.9/site-packages/httpcore/_sync/connection_pool.py", line 239, in handle_request
    connection = status.wait_for_connection(timeout=timeout)
  File "/usr/local/lib/python3.9/site-packages/httpcore/_sync/connection_pool.py", line 36, in wait_for_connection
    self._connection_acquired.wait(timeout=timeout)
  File "/usr/local/lib/python3.9/site-packages/httpcore/_synchronization.py", line 232, in wait
    raise PoolTimeout()  # pragma: nocover
httpcore.PoolTimeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/openai/_base_client.py", line 858, in _request
    response = self._client.send(request, auth=self.custom_auth, stream=stream)
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 901, in send
    response = self._send_handling_auth(
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 929, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 966, in _send_handling_redirects
    response = self._send_single_request(request)
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1002, in _send_single_request
    response = transport.handle_request(request)
  File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 228, in handle_request
    resp = self._pool.handle_request(req)
  File "/usr/local/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 83, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.PoolTimeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 66, in map_httpcore_exceptions
    yield
  File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 228, in handle_request
    resp = self._pool.handle_request(req)
  File "/usr/local/lib/python3.9/site-packages/httpcore/_sync/connection_pool.py", line 248, in handle_request
    raise exc
  File "/usr/local/lib/python3.9/site-packages/httpcore/_sync/connection_pool.py", line 239, in handle_request
    connection = status.wait_for_connection(timeout=timeout)
  File "/usr/local/lib/python3.9/site-packages/httpcore/_sync/connection_pool.py", line 36, in wait_for_connection
    self._connection_acquired.wait(timeout=timeout)
  File "/usr/local/lib/python3.9/site-packages/httpcore/_synchronization.py", line 232, in wait
    raise PoolTimeout()  # pragma: nocover
httpcore.PoolTimeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/openai/_base_client.py", line 858, in _request
    response = self._client.send(request, auth=self.custom_auth, stream=stream)
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 901, in send
    response = self._send_handling_auth(
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 929, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 966, in _send_handling_redirects
    response = self._send_single_request(request)
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1002, in _send_single_request
    response = transport.handle_request(request)
  File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 228, in handle_request
    resp = self._pool.handle_request(req)
  File "/usr/local/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 83, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.PoolTimeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/workplace/youqu/model/openai/parallel_function_calling_models.py", line 153, in parallel_function_calling_get_GPT_function_answer
    res = client.chat.completions.create(**openai_params)
  File "/usr/local/lib/python3.9/site-packages/openai/_utils/_utils.py", line 299, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/openai/resources/chat/completions.py", line 594, in create
    return self._post(
  File "/usr/local/lib/python3.9/site-packages/openai/_base_client.py", line 1055, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/usr/local/lib/python3.9/site-packages/openai/_base_client.py", line 834, in request
    return self._request(
  File "/usr/local/lib/python3.9/site-packages/openai/_base_client.py", line 880, in _request
    return self._retry_request(
  File "/usr/local/lib/python3.9/site-packages/openai/_base_client.py", line 925, in _retry_request
    return self._request(
  File "/usr/local/lib/python3.9/site-packages/openai/_base_client.py", line 880, in _request
    return self._retry_request(
  File "/usr/local/lib/python3.9/site-packages/openai/_base_client.py", line 925, in _retry_request
    return self._request(
  File "/usr/local/lib/python3.9/site-packages/openai/_base_client.py", line 887, in _request
    raise APITimeoutError(request=request) from err
openai.APITimeoutError: Request timed out.
[WARNING][2023-11-13 12:30:44][parallel_function_calling_models.py:156] - [CHATGPT] APIConnection failed
[DEBUG][2023-11-13 12:30:44][chatgpt_model.py:212] - Got final reply
[INFO][2023-11-13 12:30:44][chatgpt_model.py:231] - Current query_record.complication_count=10
[INFO][2023-11-13 12:30:44][log.py:60] - [/root/workplace/youqu/channel/http/ws_controller/socketio_handler.py:174] reply:我连接不到网络，请稍后重试
(153607) accepted ('127.0.0.1', 56374)
